Minor fixes
- various simplifications
- added a couple of helper methods
- now logs messages to stderr
- POSIX compliant
- moved to sh
- added test (based on spellcheck)
- safer escaping of paths

Signed-off-by: dubo-dubon-duponey <dubodubonduponey+github@pm.me>

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,44 +1,58 @@
-#!/usr/bin/env bash
+#!/bin/sh
 # ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★
-# P.O.SH - a piece of shcript
-# (c) 2018 Dubo Dubon Duponey <farcloser.root@gmail.com>
+# P.O.SH - a very small POSIX compliant piece of shcript
+# (c) 2018 Dubo Dubon Duponey <dubodubonduponey+github@pm.me>
 # Distributed under the terms of the MIT license
 # ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★
 
 # Source profile if here
-[ ! -f ~/.profile ] || source ~/.profile
+# shellcheck source=/dev/null
+[ -f "$HOME/.profile" ] && . "$HOME/.profile"
+
+stamp(){
+  >&2 echo "[$(date)]" "$@"
+}
+
+error(){
+  [ ! "$TERM" ] || ( [ -t 2 ] && >&2 tput setaf 1 )
+  stamp "[ERROR]" "$@"
+  [ ! "$TERM" ] || ( [ -t 2 ] && >&2 tput op )
+}
+
+warning(){
+  [ ! "$TERM" ] || ( [ -t 2 ] && >&2 tput setaf 3 )
+  stamp "[WARNING]" "$@"
+  [ ! "$TERM" ] || ( [ -t 2 ] && >&2 tput op )
+}
+
+info(){
+  [ ! "$TERM" ] || ( [ -t 2 ] && >&2 tput setaf 2 )
+  stamp "[INFO]" "$@"
+  [ ! "$TERM" ] || ( [ -t 2 ] && >&2 tput op )
+}
 
 # Enforce XCode command line tools to be here
-while [ -z "$(which git)" ]; do
-
+while ! command -v git 1>/dev/null; do
   git 2>/dev/null 1>&2
-
-  [ -z "$TERM" ] || tput setaf 3
-  echo "$(date) WARNING: You need to install XCode command line tools. You should be prompted to do so now."
-  echo "Hit enter when installation completes."
-  [ -z "$TERM" ] || tput op
-  read
-
+  warning "You need to install XCode command line tools. You should be prompted to do so now."
+  info "Hit enter when XCode installation completes."
+  read -r
 done
 
-[ -z "$TERM" ] || tput setaf 2
-echo "$(date) INFO: XCode command line tools is properly installed."
-[ -z "$TERM" ] || tput op
+info "XCode command line tools is properly installed."
 
 # Have homebrew if not here
-if [ -z "$(which brew)" ]; then
+if ! command -v brew 1>/dev/null; then
 
-  [ -z "$TERM" ] || tput setaf 3
-  echo "$(date) WARNING: You are missing homebrew. Going to install."
-  [ -z "$TERM" ] || tput op
+  warning "You are missing homebrew. Going to install."
 
-  [ ! -z "$POSH_TOKEN" ] || read -p " > Your github api token for homebrew: " POSH_TOKEN
-  [ ! -z "$POSH_TMP" ] || read -p " > Where to hold temporary files for homebrew [default to ~/tmp]: " POSH_TMP
-  [ ! -z "$POSH_BIN" ] || read -p " > Where to install homebrew [default to ~/Applications/bin]: " POSH_BIN
+  [ "$POSH_TOKEN" ] || printf "%s" " > Your github api token for homebrew: " && read -r POSH_TOKEN
+  [ "$POSH_TMP" ]   || printf "%s" " > Where to hold temporary files for homebrew [default to $HOME/tmp]: " && read -r POSH_TMP
+  [ "$POSH_BIN" ]   || printf "%s" " > Where to install homebrew [default to $HOME/Applications/bin]: " && read -r POSH_BIN
 
-  [ ! -z "$POSH_TMP" ] || POSH_TMP=~/tmp
-  [ ! -z "$POSH_BIN" ] || POSH_BIN=~/Applications/bin
-  [ ! -z "$POSH_CASK" ] || POSH_CASK=~/Applications/cask
+  POSH_TMP="${POSH_TMP:-$HOME/tmp}"
+  POSH_BIN="${POSH_BIN:-$HOME/Applications/bin}"
+  POSH_CASK="${POSH_CASK:-$HOME/Applications/cask}"
 
   mkdir -p "${POSH_BIN}/homebrew" 2>/dev/null
   mkdir -p "${POSH_TMP}/cache/homebrew" 2>/dev/null
@@ -53,58 +67,53 @@ if [ -z "$(which brew)" ]; then
       [ ! -d "${POSH_TMP}/log/homebrew" ] || \
       [ ! -d "${POSH_CASK}/app" ] || \
       [ ! -d "${POSH_CASK}/fonts" ]; then
-    [ -z "$TERM" ] || tput setaf 1
-    echo "$(date) FATAL: Failed to create folders. Check your permissions."
-    [ -z "$TERM" ] || tput op
+    error "Failed to create folders. Check your permissions."
     exit 1
   fi
 
-  cd "${POSH_BIN}"
-  curl -s -S -L https://github.com/mxcl/homebrew/tarball/master 2>/dev/null | tar xz --strip 1 -C homebrew
-  cd - > /dev/null
+  curl -s -S -L https://github.com/mxcl/homebrew/tarball/master 2>/dev/null | tar xz --strip 1 -C "${POSH_BIN}/homebrew"
 
   if [ ! -f "${POSH_BIN}/homebrew/bin/brew" ]; then
-    [ -z "$TERM" ] || tput setaf 1
-    echo "$(date) FATAL: Failed to retrieve homebrew from github. Network down?"
-    [ -z "$TERM" ] || tput op
+    error "Failed to retrieve homebrew from github. Network down?"
     exit 1
   fi
 
-  rm -Rf ${POSH_BIN}/homebrew/share/doc/homebrew
+  # rm -Rf ${POSH_BIN}/homebrew/share/doc/homebrew
 
-  ${POSH_BIN}/homebrew/bin/brew update
-  ${POSH_BIN}/homebrew/bin/brew install bash-completion
+  "${POSH_BIN}/homebrew/bin/brew" update
+  "${POSH_BIN}/homebrew/bin/brew" install bash-completion
 
-  cat <<- EOF > ~/.posh_brew
+  cat <<- EOF > "$HOME/.posh_brew"
   # ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★
   # ★ kingpin ＆ homebrew        ★
   # ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★
 
-  export POSH_TMP=${POSH_TMP}
-  export POSH_BIN=${POSH_BIN}
+  export POSH_TMP="${POSH_TMP}"
+  export POSH_BIN="${POSH_BIN}"
 
-  export PATH=\${POSH_BIN}/homebrew/bin:\${POSH_BIN}/homebrew/sbin:\${PATH}
+  export PATH="\${POSH_BIN}/homebrew/bin:\${POSH_BIN}/homebrew/sbin:\${PATH}"
   export HOMEBREW_GITHUB_API_TOKEN=${POSH_TOKEN}
-  export HOMEBREW_CACHE=\${POSH_TMP}/cache/homebrew
-  export HOMEBREW_TEMP=\${POSH_TMP}/tmp/homebrew
-  export HOMEBREW_LOGS=\${POSH_TMP}/log/homebrew
-  . \$(brew --prefix)/etc/bash_completion
-  export HOMEBREW_CASK_OPTS="--appdir=~/Applications/cask/app --fontdir=~/Applications/cask/fonts"
+  export HOMEBREW_CACHE="\${POSH_TMP}/cache/homebrew"
+  export HOMEBREW_TEMP="\${POSH_TMP}/tmp/homebrew"
+  export HOMEBREW_LOGS="\${POSH_TMP}/log/homebrew"
+  export HOMEBREW_CASK_OPTS="--appdir=\$HOME/Applications/cask/app --fontdir=\$HOME/Applications/cask/fonts"
+  # shellcheck source=/dev/null
+  . "\$(brew --prefix)/etc/bash_completion"
 EOF
 
-  touch .profile
-  if [[ -z "$(cat .profile | grep posh_brew)" ]]; then
-    cat <<- EOF >> ~/.profile
+  touch "$HOME/.profile"
+  if ! grep -q posh_brew "$HOME/.profile"; then
+    cat <<- EOF >> "$HOME/.profile"
     # ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★
-    # ★ kingpin                    ★
+    # ★ tarmac                     ★
     # ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★
-    . ~/.posh_brew
+    # shellcheck source=$HOME/.posh_node
+    . "\$HOME/.posh_brew"
 EOF
   fi
 
-  source ~/.profile
+  # shellcheck source=/dev/null
+  . "$HOME/.profile"
 fi
 
-[ -z "$TERM" ] || tput setaf 2
-echo "$(date) INFO: Homebrew is properly installed and up to date."
-[ -z "$TERM" ] || tput op
+info "Homebrew is properly installed and up to date."
