Fix
Signed-off-by: dubo-dubon-duponey <dubodubonduponey+github@pm.me>

diff --git a/init b/init
--- a/init
+++ b/init
@@ -6,8 +6,40 @@ set -o errexit -o errtrace -o functrace -o nounset -o pipefail
 # Distributed under the terms of the MIT license
 # ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★
 
-# shellcheck source=tooling/helpers.sh
-. "$(cd "$(dirname "${BASH_SOURCE[0]:-$PWD}")" 2>/dev/null 1>&2 && pwd)"/tooling/helpers.sh
+COLOR_RED=1
+COLOR_GREEN=2
+COLOR_YELLOW=3
+
+# Prefix a date to a log line and output to stderr
+logger::stamp(){
+  local color="$1"
+  local level="$2"
+  local i
+  shift
+  shift
+  [ "$TERM" ] && [ -t 2 ] && >&2 tput setaf "$color"
+  for i in "$@"; do
+    >&2 printf "[%s] [%s] %s\n" "$(date)" "$level" "$i"
+  done
+  [ "$TERM" ] && [ -t 2 ] && >&2 tput op
+}
+
+logger::info(){
+  logger::stamp "$COLOR_GREEN" "INFO" "$@"
+}
+
+logger::warning(){
+  logger::stamp "$COLOR_YELLOW" "WARNING" "$@"
+}
+
+logger::error(){
+  logger::stamp "$COLOR_RED" "ERROR" "$@"
+}
+
+curl::get(){
+  >&2 printf " > Downloading %s\n" "$@"
+  curl --proto '=https' --tlsv1.3 -sSfL --compressed "$1"
+}
 
 # Source profile if here
 # shellcheck source=/dev/null
